### ISSUE TITLE
Figure out some good ways to display graphs/data

### ISSUE THREAD

**Issue by nickclason** [nickclason/Senior-Design#5]

**Comment by swansobp** [comment]
Essential JS 2 has a good widget for stocks, doesn't necessarily look pretty but we could potentially use this and try to style it

https://ej2.syncfusion.com/angular/demos/#/bootstrap5/stock-chart/multi-pane

**Comment by nickclason** [comment]
This looks good and seems to have a lot of other stuff we could use as well. I really like the navigation and layout component stuff that they have. 

Would make the app look a lot cleaner and reduce some of the weird custom stuff that I started to do for making things like the menu bar 👌👌👌
